const WeatherControlTypes = {
  SET_LOADING: "SET_LOADING",
  SET_CURRENT_PLACE: "SET_CURRENT_PLACE",
  FETCH_FORECAST: "FETCH_FORECAST",
  FETCH_FORECAST_SUCCESS: "FETCH_FORECAST_SUCCESS",
  SET_ACTIVE_DAY: "SET_ACTIVE_DAY",
};

export default WeatherControlTypes;
